encyclopedia/urls.py
from django.urls import path, re_path

from . import views

app_name = "encyclopedia"
urlpatterns = [
    path("", views.index, name="index"),
    re_path(r"^wiki/(?P<title>\w*)/$", views.wiki, name="wiki"),
    path("search", views.search, name="search"),
    path("new", views.new, name="new"),
    path("edit/<str:title>", views.edit, name="edit")
]

wiki/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include("encyclopedia.urls"))
]

encyclopedia/models.py
from django.db import models

# Create your models here.

encyclopedia/views.py
from django.shortcuts import render, redirect
from django.urls import reverse
from django import forms
from random import randrange
from markdown2 import Markdown

from . import util

class NewForm(forms.Form):
    title = forms.CharField(label= "Title")
    content = forms.CharField(label="Content", widget=forms.Textarea)

    def clean_title(self):
        data = self.cleaned_data.get("title")
        if data in util.list_entries():
            raise forms.ValidationError("Wiki entry already exists.")
        return data

def index(request):
    return render(request, "encyclopedia/index.html", {
            "entries": util.list_entries
    })            

def wiki(request, title):
    if len(title) == 0:
        entries = util.list_entries()
        title = entries[randrange(len(entries))]
    file = util.get_entry(title)
    if not file:
        return render(request, "encyclopedia/notFound.html")
    else:
        markdowner = Markdown()
        return render(request, "encyclopedia/wiki.html", {
            "title": title.capitalize(),
            "file": markdowner.convert(file)
        })

def new(request):
    if request.method == "POST":
        form = NewForm(request.POST)
        if form.is_valid():
            data = form.cleaned_data
            util.save_entry(data["title"], data["content"])
            return redirect('encyclopedia:wiki', title= data["title"])
        else:   
            return render(request, "encyclopedia/new.html", {
                "form": form
            })
    return render(request, "encyclopedia/new.html", {
        "form": NewForm()
    })

def edit(request, title):
    if request.method == "POST":
        util.save_entry(title, request.POST['content']) 
        return redirect('encyclopedia:wiki', title= title)
    return render(request, "encyclopedia/edit.html", {
        # "form": NewForm(initial= {'content': util.get_entry(title)}),
        "title": title,
        "content": util.get_entry(title)
    })

def search(request):
    search = request.GET.get("q")
    file = util.get_entry(search)
    if file == None:
        results = list()
        for entry in util.list_entries():
            if entry.lower().find(search.lower()) != -1:
                results.append(entry)
        return render(request, "encyclopedia/results.html", {
            "entries": results
        })
    else:
        return render(request, "encyclopedia/wiki.html", {
            "title": search,
            "file": util.get_entry(search)
        })

encyclopedia/templates/encyclopedia/edit.html
{% extends 'encyclopedia/layout.html' %}

{% block title %}
    Edit - {{ title }}
{% endblock %}

{% block body %}
    <h1>Edit {{ title }} </h1>
    <form action="{% url 'encyclopedia:edit' title=title %}" method="POST" name="entryForm">
        {% csrf_token %}
        <div style="margin-bottom: 20%">
            <!-- Title: {{ title }}<br> -->
            Content: <br>
            <textarea name="content" rows="50" cols="100">{{ content }}</textarea><br>
            <input type="submit">
        </div>
    </form> 
{% endblock %}

encyclopedia/templates/encyclopedia/index.html
{% extends "encyclopedia/layout.html" %}

{% block title %}
    Encyclopedia
{% endblock %}

{% block body %}
    <h1>All Pages</h1>

    <ul>
        {% for entry in entries %}
            <li>
                <a href="{% url 'encyclopedia:wiki' title=entry %}">{{ entry }}</a>
            </li>
        {% endfor %}
    </ul>

{% endblock %}

encyclopedia/templates/encyclopedia/layout.html
{% load static %}

<!DOCTYPE html>

<html lang="en">
    <head>
        <title>{% block title %}{% endblock %}</title>
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
        <link href="{% static 'encyclopedia/styles.css' %}" rel="stylesheet">
    </head>
    <body>
        <div class="row">
            <div class="sidebar col-lg-2 col-md-3">
                <h2>Wiki</h2>
                <form action="search">
                    <input class="search" type="text" name="q" placeholder="Search Encyclopedia">
                </form>
                <div>
                    <a href="{% url 'encyclopedia:index' %}">Home</a>
                </div>
                <div>
                    <a href="{% url 'encyclopedia:new' %}">Create New Page</a>
                </div>
                <div>
                    <a href="{% url 'encyclopedia:wiki' title='' %}">Random Page</a>
                </div>
                {% block nav %}
                {% endblock %}
            </div>
            <div class="main col-lg-10 col-md-9">
                {% block body %}
                {% endblock %}
            </div>
        </div>

    </body>
</html>

encyclopedia/templates/encyclopedia/new.html
{% extends 'encyclopedia/layout.html' %}

{% block title %}
    Create New Entry
{% endblock %}

{% block body %}
    <h1>Create New Entry</h1>
    <form action="{% url 'encyclopedia:new' %}" method="POST" name="entryForm">
        {% csrf_token %}
        <div style="margin-bottom: 20%">
            <table width="100%">
                {{ form }}
            </table>
            <input style="left: 20%; position: absolute;" type="submit">
        </div>
    </form> 
{% endblock %}

encyclopedia/templates/encyclopedia/notFound.html
{% extends "encyclopedia/layout.html" %}

{% block title %}
    Page Not Found
{% endblock %}

{% block body %}
    <h1>The requested page was not found.</h1>
{% endblock %}

encyclopedia/templates/encyclopedia/results.html
{% extends "encyclopedia/layout.html" %}

{% block title %}
    Encyclopedia
{% endblock %}

{% block body %}
    <h1>Search Results</h1>

    <ul>
        {% for entry in entries %}
            <li>
                <a href="wiki/{{ entry }}">{{ entry }}</a>
            </li>
            {% empty %}
                No Results Found.
        {% endfor %}
    </ul>

{% endblock %}

encyclopedia/templates/encyclopedia/wiki.html
{% extends "encyclopedia/layout.html" %}

{% block title %}
    {{ title }}
{% endblock %}

{% block body %}
    <a href="{% url 'encyclopedia:edit' title=title%}">Edit</a> <br>
    {{ file|safe }}
{% endblock %}